# ⚙️ .github/workflows/build-resume.yml

name: Build LaTeX Resume

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        run: |
          docker run --rm --user="$(id -u):$(id -g)" --net=none -v "${{ github.workspace }}:/data" leplusorg/latex latexmk -outdir=/data -pdf /data/resume.tex

      - name: Upload Resume PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf