# .github/workflows/auto-release-on-commit.yml

name: Auto-Release Resume on Commit

on:
  push:
    branches:
      - main
      - master
    # Only run the workflow if the resume.tex file was changed
    paths:
      - 'resume.tex'
  
  # Also allow manual trigger for convenience
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      # This permission is essential to create releases
      contents: write

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Compile the LaTeX file to produce the PDF
      - name: Compile LaTeX to PDF
        run: |
          docker run --rm --user="$(id -u):$(id -g)" --net=none -v "${{ github.workspace }}:/data" leplusorg/latex latexmk -outdir=/data -pdf /data/resume.tex

      # Step 3: Generate a date-based tag name
      # Format: vYYYY.MM.DD.HHMMSS (e.g., v2024.05.16.143055)
      - name: Generate date-based tag
        id: generate_tag
        run: echo "TAG_NAME=v$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV

      # Step 4: Create the GitHub Release and upload the PDF
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Use the tag generated in the previous step
          tag_name: ${{ env.TAG_NAME }}
          # Name the release clearly
          name: "Resume - ${{ env.TAG_NAME }}"
          # The file(s) to upload as release assets
          files: resume.pdf
          # A description for the release, linking back to the commit
          body: |
            Automatic release of the latest resume.
            Compiled from commit: `${{ github.sha }}`
          # We want this to be a final release, not a draft or prerelease
          draft: false
          prerelease: false
